spring:
  mail:
    host: smtp.qq.com
    username: haven-just@qq.com
    password: xueipuxfzchkigeh
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    username: guest
    password: Justholdway521
    virtual-host: /
    host: 127.0.0.1
    port: 5672
